"""Signal 1 — LLM attribution assessment (Groq-prompted classifier).

What it measures:
    Asks a capable instruction-tuned model (via Groq) to judge how likely the
    text was AI-generated, returning a *structured* assessment rather than a
    free-form opinion. This is the "prompted LLM classifier" option from the
    architecture narrative (step 3).

Output:
    A normalized "AI-ness" score ``score in [0, 1]`` (higher = more likely AI),
    taken from the model's ``ai_likelihood``. With ``return_detail=True`` the
    full structured assessment (reasoning + indicators) is returned too — handy
    for verification and for the confidence scorer in M4.

Note:
    Network/API dependent. Failures raise ``GroqSignalError`` so the caller can
    decide how to degrade (the endpoint catches it and still returns a
    content_id).
"""

from __future__ import annotations

import json
import os
from typing import Optional

from dotenv import load_dotenv

load_dotenv()

# Default Groq model. Configurable via env so it can be swapped without code.
DEFAULT_MODEL = os.environ.get("GROQ_MODEL", "llama-3.3-70b-versatile")

_SYSTEM_PROMPT = (
    "You are a forensic text-provenance analyst. Given a passage, judge how "
    "likely it was generated by an AI language model versus written by a human. "
    "Weigh signals like fluency uniformity, generic phrasing, lack of concrete "
    "lived detail, and predictable structure (AI-leaning) against bursty "
    "rhythm, idiosyncrasy, specific detail, and surprising word choice "
    "(human-leaning). You only assess and label; you never accuse or punish.\n\n"
    "Respond with a single JSON object and nothing else, with these keys:\n"
    '  "ai_likelihood": number between 0 and 1 (probability the text is AI-generated),\n'
    '  "assessment": one of "likely_ai", "uncertain", "likely_human",\n'
    '  "indicators": array of up to 4 short strings naming what drove the judgment,\n'
    '  "reasoning": one or two sentences explaining the call.'
)

_client = None


class GroqSignalError(RuntimeError):
    """Raised when the Groq attribution call fails or returns unusable output."""


def _get_client():
    """Lazily build and cache the Groq client."""
    global _client
    if _client is not None:
        return _client
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise GroqSignalError("GROQ_API_KEY is not set (check your .env)")
    try:
        from groq import Groq
    except ImportError as exc:  # pragma: no cover
        raise GroqSignalError("groq package not installed (pip install groq)") from exc
    _client = Groq(api_key=api_key)
    return _client


def _clamp01(value) -> float:
    try:
        return max(0.0, min(1.0, float(value)))
    except (TypeError, ValueError):
        raise GroqSignalError(f"ai_likelihood was not a number: {value!r}")


def groq_attribution_signal(
    text: str,
    *,
    model: Optional[str] = None,
    return_detail: bool = False,
):
    """Compute the Signal 1 AI-ness score for ``text`` via Groq.

    Args:
        text: raw submission text.
        model: Groq model id (defaults to ``DEFAULT_MODEL``).
        return_detail: if True, return the full structured assessment dict;
            otherwise return just the float score.

    Returns:
        ``float`` in [0, 1] (higher = more AI-like), or a detail dict.

    Raises:
        ValueError: if ``text`` is empty.
        GroqSignalError: on API/parse failure.
    """
    if not text or not text.strip():
        raise ValueError("text must be a non-empty string")

    client = _get_client()
    try:
        completion = client.chat.completions.create(
            model=model or DEFAULT_MODEL,
            temperature=0,  # deterministic-as-possible judgment
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": f"Assess this passage:\n\n{text}"},
            ],
        )
    except Exception as exc:  # network, auth, rate-limit, etc.
        raise GroqSignalError(f"Groq API call failed: {exc}") from exc

    raw = completion.choices[0].message.content
    try:
        parsed = json.loads(raw)
    except (json.JSONDecodeError, TypeError) as exc:
        raise GroqSignalError(f"Groq returned non-JSON output: {raw!r}") from exc

    score = _clamp01(parsed.get("ai_likelihood"))

    if return_detail:
        return {
            "signal": "groq_attribution",
            "model": model or DEFAULT_MODEL,
            "score": score,  # x1 in [0, 1], higher = more AI-like
            "assessment": parsed.get("assessment"),
            "indicators": parsed.get("indicators", []),
            "reasoning": parsed.get("reasoning"),
        }
    return score


if __name__ == "__main__":
    # Independent verification: call the function directly on a few inputs and
    # inspect the output BEFORE wiring it into the endpoint.
    samples = {
        "AI-ish (fluent, generic)": (
            "In today's fast-paced world, it is important to recognize that "
            "effective communication plays a crucial role in fostering "
            "meaningful connections and driving successful outcomes."
        ),
        "human (specific, bursty)": (
            "My grandmother's kitchen smelled of burnt cardamom. She'd swat my "
            "hand from the pan, mutter in Mooré, then sneak me the crispy bits "
            "anyway. I never learned the recipe. I wish I had."
        ),
    }
    for label, sample in samples.items():
        detail = groq_attribution_signal(sample, return_detail=True)
        print(f"\n=== {label} ===")
        print(json.dumps(detail, indent=2, ensure_ascii=False))
